from odoo import _

from odoo.addons.energy_communities.config import (
    STATE_CLOSED,
    STATE_CLOSED_PLANNED,
    STATE_IN_PROGRESS,
    STATE_LABELS,
    STATE_NONE,
    STATE_PAUSED,
)

CONTRACT_STATUS_PAUSED = STATE_PAUSED
CONTRACT_STATUS_IN_PROGRESS = STATE_IN_PROGRESS
CONTRACT_STATUS_CLOSED_PLANNED = STATE_CLOSED_PLANNED
CONTRACT_STATUS_CLOSED = STATE_CLOSED
CONTRACT_STATUS_NONE = STATE_NONE


CONTRACT_STATUS_VALUES = [
    (CONTRACT_STATUS_PAUSED, STATE_LABELS[CONTRACT_STATUS_PAUSED]),
    (CONTRACT_STATUS_IN_PROGRESS, STATE_LABELS[CONTRACT_STATUS_IN_PROGRESS]),
    (CONTRACT_STATUS_CLOSED_PLANNED, STATE_LABELS[CONTRACT_STATUS_CLOSED_PLANNED]),
    (CONTRACT_STATUS_CLOSED, STATE_LABELS[CONTRACT_STATUS_CLOSED]),
]

PACK_CONTRACT_STATUS_VALUES = CONTRACT_STATUS_VALUES + [
    (CONTRACT_STATUS_NONE, STATE_LABELS[CONTRACT_STATUS_NONE])
]

CONTRACT_ACTION_NONE = STATE_NONE
CONTRACT_ACTION_ACTIVATE = "activate"
CONTRACT_ACTION_MODIFICATION = "modification"
CONTRACT_ACTION_REOPEN = "reopen"
CONTRACT_ACTION_CLOSE = "close"

CONTRACT_ACTION_LABELS = {
    CONTRACT_ACTION_NONE: STATE_LABELS[CONTRACT_ACTION_NONE],
    CONTRACT_ACTION_ACTIVATE: _("Activate"),
    CONTRACT_ACTION_MODIFICATION: _("Modification"),
    CONTRACT_ACTION_REOPEN: _("Reopen"),
    CONTRACT_ACTION_CLOSE: _("Close"),
}

SERVICE_INVOICING_EXECUTED_ACTION_VALUES = [
    (CONTRACT_ACTION_ACTIVATE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_ACTIVATE]),
    (
        CONTRACT_ACTION_MODIFICATION,
        CONTRACT_ACTION_LABELS[CONTRACT_ACTION_MODIFICATION],
    ),
    (CONTRACT_ACTION_REOPEN, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_REOPEN]),
    (CONTRACT_ACTION_CLOSE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_CLOSE]),
]

SALE_ORDER_SERVICE_INVOICING_ACTION_VALUES = [
    (CONTRACT_ACTION_NONE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_NONE])
] + SERVICE_INVOICING_EXECUTED_ACTION_VALUES[:-1]

SALE_ORDER_SERVICE_INVOICING_ACTION_DEFAULT_VALUE = CONTRACT_ACTION_NONE

CONTRACT_CLOSING_ACTION_VALUES = [
    (CONTRACT_ACTION_NONE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_NONE])
] + SERVICE_INVOICING_EXECUTED_ACTION_VALUES

CONTRACT_CLOSING_ACTION_DEFAULT_VALUE = CONTRACT_ACTION_NONE

PACK_PRODUCT_PARENT_CATEG_REF = "energy_communities.product_category_pack"
SERVICE_PRODUCT_PARENT_CATEG_REF = "energy_communities.product_category_service"
SHARE_PRODUCTS_CATEG_REFS = [
    "energy_communities.product_category_share_recurring_fee_pack",
    "cooperator.product_category_company_share",
    "energy_communities.product_category_company_voluntary_share",
    "energy_communities_cooperator.product_category_company_voluntary_share",
]
ASSIGNABLE_PACKS_TO_PARTNER_CATEG_REFS = [
    "energy_communities.product_category_recurring_fee_pack"
]

RECURRING_RULE_MONTHLY = "monthly"
RECURRING_RULE_MONTHLY_LAST_DAY = "monthlylastday"

DEFAULT_PRICELIST_BASE_PRICE = "standard_price"
DEFAULT_PRICELIST_COMPUTE_FIXED = "fixed"
DEFAULT_PRICELIST_DISCOUNT_POLICY = "without_discount"

INVOICE_SELFCONSUMPTION = "selfconsumption"
INVOICE_MEMBERSHIP = "membership"
INVOICE_OTHER = "other"
INVOICE_SERVICETYPE_LABELS = [
    (INVOICE_SELFCONSUMPTION, _("Selfconsumption")),
    (INVOICE_MEMBERSHIP, _("Membership")),
    (INVOICE_OTHER, _("Other")),
]
