from odoo import _

from odoo.addons.energy_communities.config import (
    STATE_CLOSED,
    STATE_CLOSED_PLANNED,
    STATE_IN_PROGRESS,
    STATE_LABELS,
    STATE_NONE,
    STATE_PAUSED,
)
from odoo.addons.energy_communities_cooperator.config import (
    COOP_SHARE_PRODUCT_CATEG_REF,
    COOP_VOLUNTARY_SHARE_PRODUCT_CATEG_REF,
)

# Service Invoicing
CONTRACT_STATUS_PAUSED = STATE_PAUSED
CONTRACT_STATUS_IN_PROGRESS = STATE_IN_PROGRESS
CONTRACT_STATUS_CLOSED_PLANNED = STATE_CLOSED_PLANNED
CONTRACT_STATUS_CLOSED = STATE_CLOSED
CONTRACT_STATUS_NONE = STATE_NONE


CONTRACT_STATUS_VALUES = [
    (CONTRACT_STATUS_PAUSED, STATE_LABELS[CONTRACT_STATUS_PAUSED]),
    (CONTRACT_STATUS_IN_PROGRESS, STATE_LABELS[CONTRACT_STATUS_IN_PROGRESS]),
    (CONTRACT_STATUS_CLOSED_PLANNED, STATE_LABELS[CONTRACT_STATUS_CLOSED_PLANNED]),
    (CONTRACT_STATUS_CLOSED, STATE_LABELS[CONTRACT_STATUS_CLOSED]),
]

PACK_CONTRACT_STATUS_VALUES = CONTRACT_STATUS_VALUES + [
    (CONTRACT_STATUS_NONE, STATE_LABELS[CONTRACT_STATUS_NONE])
]

CONTRACT_ACTION_NONE = STATE_NONE
CONTRACT_ACTION_ACTIVATE = "activate"
CONTRACT_ACTION_MODIFICATION = "modification"
CONTRACT_ACTION_REOPEN = "reopen"
CONTRACT_ACTION_CLOSE = "close"

CONTRACT_ACTION_LABELS = {
    CONTRACT_ACTION_NONE: STATE_LABELS[CONTRACT_ACTION_NONE],
    CONTRACT_ACTION_ACTIVATE: _("Activate"),
    CONTRACT_ACTION_MODIFICATION: _("Modification"),
    CONTRACT_ACTION_REOPEN: _("Reopen"),
    CONTRACT_ACTION_CLOSE: _("Close"),
}

SERVICE_INVOICING_EXECUTED_ACTION_VALUES = [
    (CONTRACT_ACTION_ACTIVATE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_ACTIVATE]),
    (
        CONTRACT_ACTION_MODIFICATION,
        CONTRACT_ACTION_LABELS[CONTRACT_ACTION_MODIFICATION],
    ),
    (CONTRACT_ACTION_REOPEN, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_REOPEN]),
    (CONTRACT_ACTION_CLOSE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_CLOSE]),
]

SALE_ORDER_SERVICE_INVOICING_ACTION_VALUES = [
    (CONTRACT_ACTION_NONE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_NONE])
] + SERVICE_INVOICING_EXECUTED_ACTION_VALUES[:-1]

SALE_ORDER_SERVICE_INVOICING_ACTION_DEFAULT_VALUE = CONTRACT_ACTION_NONE

CONTRACT_CLOSING_ACTION_VALUES = [
    (CONTRACT_ACTION_NONE, CONTRACT_ACTION_LABELS[CONTRACT_ACTION_NONE])
] + SERVICE_INVOICING_EXECUTED_ACTION_VALUES

CONTRACT_CLOSING_ACTION_DEFAULT_VALUE = CONTRACT_ACTION_NONE

RECURRING_RULE_MONTHLY = "monthly"
RECURRING_RULE_MONTHLY_LAST_DAY = "monthlylastday"

DEFAULT_PRICELIST_BASE_PRICE = "standard_price"
DEFAULT_PRICELIST_COMPUTE_FIXED = "fixed"
DEFAULT_PRICELIST_DISCOUNT_POLICY = "without_discount"


# Accounting
COOP_ACCOUNT_REF = "l10n_es.{}_account_pymes_100"
COOP_ACCOUNT_REF_NONPROFIT = "l10n_es.{}_account_assoc_720"
COOP_ACCOUNT_REF_IN_COMPANY = "l10n_es.{}_account_common_4400"
SELFCONSUMPTION_ACCOUNT_REF = "l10n_es.{}_account_common_7050"
SELFCONSUMPTION_ACCOUNT_REF_EXPENSE = "l10n_es.{}_account_common_607"
PLATFORM_ACCOUNT_REF = "l10n_es.{}_account_common_7050"
PLATFORM_ACCOUNT_REF_EXPENSE = "l10n_es.{}_account_common_607"
RECURRING_FEE_ACCOUNT_REF = "l10n_es.{}_account_common_7050"
RECURRING_FEE_ACCOUNT_REF_EXPENSE = "l10n_es.{}_account_common_607"
RECURRING_FEE_ACCOUNT_REF_NONPROFIT = "l10n_es.{}_account_assoc_720"
VSIR_ACCOUNT_REF = "l10n_es.{}_account_common_6624"

CANARY_COOP_ACCOUNT_REF = "l10n_es_igic.{}_account_pymes_canary_100"
CANARY_COOP_ACCOUNT_REF_NONPROFIT = "l10n_es_igic.{}_account_assoc_canary_720"
CANARY_RECURRING_FEE_ACCOUNT_REF_NONPROFIT = "l10n_es_igic.{}_account_assoc_canary_720"

# Packs & Services
PACK_TYPE_NONE = STATE_NONE
PACK_TYPE_PLATFORM = "platform_pack"
PACK_TYPE_RECURRING_FEE = "recurring_fee_pack"
PACK_TYPE_SHARE_RECURRING_FEE = "share_recurring_fee_pack"
PACK_TYPE_SELFCONSUMPTION = "selfconsumption_pack"

PACK_TYPE_LABELS = {
    PACK_TYPE_NONE: STATE_LABELS[PACK_TYPE_NONE],
    PACK_TYPE_PLATFORM: _("Platform Pack"),
    PACK_TYPE_RECURRING_FEE: _("Recurring fee Pack"),
    PACK_TYPE_SHARE_RECURRING_FEE: _("Share with recurring fee pack"),
    PACK_TYPE_SELFCONSUMPTION: _("Selfconsumption Pack"),
}

PACK_TYPE_VALUES = [
    (PACK_TYPE_NONE, PACK_TYPE_LABELS[PACK_TYPE_NONE]),
    (PACK_TYPE_PLATFORM, PACK_TYPE_LABELS[PACK_TYPE_PLATFORM]),
    (PACK_TYPE_RECURRING_FEE, PACK_TYPE_LABELS[PACK_TYPE_RECURRING_FEE]),
    (PACK_TYPE_SHARE_RECURRING_FEE, PACK_TYPE_LABELS[PACK_TYPE_SHARE_RECURRING_FEE]),
    (PACK_TYPE_SELFCONSUMPTION, PACK_TYPE_LABELS[PACK_TYPE_SELFCONSUMPTION]),
]

PACK_TYPE_DEFAULT_VALUE = PACK_TYPE_NONE

PACK_PRODUCT_PARENT_CATEG_REF = "energy_communities.product_category_pack"
SERVICE_PRODUCT_PARENT_CATEG_REF = "energy_communities.product_category_service"

COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF = (
    "energy_communities.product_category_share_recurring_fee_pack"
)
PLATFORM_PACK_PRODUCT_CATEG_REF = (
    "energy_communities_service_invoicing.product_category_platform_pack"
)
RECURRING_FEE_PACK_PRODUCT_CATEG_REF = (
    "energy_communities.product_category_recurring_fee_pack"
)
SELFCONSUMPTION_PACK_PRODUCT_CATEG_REF = (
    "energy_selfconsumption.product_category_selfconsumption_pack"
)

PLATFORM_SERVICE_PRODUCT_CATEG_REF = (
    "energy_communities_service_invoicing.product_category_platform_service"
)
RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF = (
    "energy_communities.product_category_recurring_fee_service"
)
SHARE_RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF = (
    "energy_communities.product_category_share_recurring_fee_service"
)
SELFCONSUMPTION_SERVICE_PRODUCT_CATEG_REF = (
    "energy_selfconsumption.product_category_selfconsumption_service"
)

SHARE_PRODUCTS_CATEG_REFS = [
    COOP_SHARE_PRODUCT_CATEG_REF,
    COOP_VOLUNTARY_SHARE_PRODUCT_CATEG_REF,
    COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
]

ASSIGNABLE_PACKS_TO_PARTNER_CATEG_REFS = [RECURRING_FEE_PACK_PRODUCT_CATEG_REF]

PACK_PROD_CATEG_REF_REL_TO_SERVICE_PROD_CATEG_REF = {
    RECURRING_FEE_PACK_PRODUCT_CATEG_REF: RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
    COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF: SHARE_RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
    PLATFORM_PACK_PRODUCT_CATEG_REF: PLATFORM_SERVICE_PRODUCT_CATEG_REF,
    SELFCONSUMPTION_PACK_PRODUCT_CATEG_REF: SELFCONSUMPTION_SERVICE_PRODUCT_CATEG_REF,
}

PACK_PROD_CATEG_REF_REL_TO_PACK_TYPES = {
    RECURRING_FEE_PACK_PRODUCT_CATEG_REF: PACK_TYPE_RECURRING_FEE,
    COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF: PACK_TYPE_SHARE_RECURRING_FEE,
    PLATFORM_PACK_PRODUCT_CATEG_REF: PACK_TYPE_PLATFORM,
    SELFCONSUMPTION_PACK_PRODUCT_CATEG_REF: PACK_TYPE_SELFCONSUMPTION,
}

INVOICE_SELFCONSUMPTION = "selfconsumption"
INVOICE_MEMBERSHIP = "membership"
INVOICE_OTHER = "other"
INVOICE_SERVICETYPE_LABELS = [
    (INVOICE_SELFCONSUMPTION, _("Selfconsumption")),
    (INVOICE_MEMBERSHIP, _("Membership")),
    (INVOICE_OTHER, _("Other")),
]

FEE_PACKS = [
    COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
    RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
]
ALL_PACKS = FEE_PACKS + [
    PLATFORM_PACK_PRODUCT_CATEG_REF,
    SELFCONSUMPTION_PACK_PRODUCT_CATEG_REF,
]
