---
image: ghcr.io/oca/oca-ci/py3.8-odoo14.0:latest
stages:
  - test

services:
  - postgres:12

variables:
  POSTGRES_DB: project_ci_test
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: "odoo"
  RUNNER_HOME: '/home/gitlab-runner'
  PIP_INDEX_URL: 'https://pypi.org/simple'

before_script:
  - pip install python-slugify python-keycloak

test:
  stage: test
  tags:
    - postgres
    - docker
  variables:
    MAKEPOT: "1"
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:deps[collapsed=true]\r\e[0KInstall addons and dependencies"
    - oca_install_addons
    - echo -e "\e[0Ksection_end:`date +%s`:deps\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:check_dev[collapsed=true]\r\e[0KCheck development status"
    - manifestoo -d . check-dev-status --default-dev-status=Beta
    - echo -e "\e[0Ksection_end:`date +%s`:check_dev\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:init_db[collapsed=true]\r\e[0KInitialize test db"
    - oca_init_test_database
    - echo -e "\e[0Ksection_end:`date +%s`:init_db\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:test[collapsed=true]\r\e[0KRun tests"
    - oca_run_tests
    - coverage xml
    - echo -e "\e[0Ksection_end:`date +%s`:test\r\e[0K"
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
       - coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
