[[config]]
name = "odoo-ce"
odoo_path = "/home/juan-pe/.pyenv/versions/3.11.7/envs/odoo-ce/lib/python3.11/site-packages/odoo"
addons_paths = ["${workspaceFolder}", "/home/juan-pe/.pyenv/versions/3.11.7/envs/odoo-ce/lib/python3.11/site-packages/odoo/addons"]
python_path = "/home/juan-pe/.pyenv/versions/3.11.7/envs/odoo-ce/bin/python3"
