from . import account_move
from . import contract
from . import contract_line
from . import distribution_table
from . import distribution_table_csv_report
from . import partner
from . import product
from . import project
from . import selfconsumption
from . import supply_point
from . import supply_point_assignation
