_CE_CREATION_API_PAYLOAD = {
    "company_id": 1,
    "email_from": "dani.quilez@gmail.com",
    "name": "ce_source_creation_ce_proposal  submission: 1385",
    "metadata": [
        {"key": "current_lang", "value": "es_ES"},
        {"key": "ce_fiscal_name", "value": "TEST CE CREATION fiscal name"},
        {"key": "ce_name", "value": "TEST CE CREATION name"},
        {"key": "ce_long_description", "value": "test ce creation long desc"},
        {"key": "ce_description", "value": "test ce creation desc"},
        {"key": "ce_address", "value": "cami ral"},
        {"key": "ce_city", "value": "mataró"},
        {"key": "ce_state", "value": "barcelona"},
        {"key": "ce_zip", "value": "08301"},
        {
            "key": "ce_services",
            "value": "energy_action_collective_purchases,energy_action_renewable_energy",
        },
        {"key": "ce_number_of_members", "value": "10"},
        {"key": "contact_person_name", "value": "contact name"},
        {"key": "contact_person_surname", "value": "contact surname"},
        {"key": "email_from", "value": "cn.cs@test.com"},
        {"key": "contact_phone", "value": "1234"},
        {"key": "contact2_firstname", "value": "contact 2 name"},
        {"key": "contact2_surname", "value": "contact 2 surname"},
        {"key": "contact2_email", "value": "cn.cs+2@test.com"},
        {"key": "contact2_phone", "value": "5678"},
        {"key": "comments", "value": "test"},
        {"key": "terms_conditions_social_economy", "value": "1"},
        {"key": "source_xml_id", "value": "ce_source_creation_ce_proposal"},
        {"key": "ce_current_lang", "value": "eu_ES"},
        {"key": "ce_constitution_status", "value": "in_definition"},
        {"key": "ce_legal_form", "value": "cooperative"},
        {"key": "ce_type", "value": "citizen"},
        {"key": "known_coordinator", "value": "yes"},
        {"key": "entry_id", "value": "1385"},
        {"key": "terms_conditions", "value": "1"},
        {"key": "coordinator_landing_id", "value": "9411"},
        {"key": "allow_send_info_about_services", "value": "1"},
        {"key": "coordinator_landing_name", "value": "Energética Coop"},
    ],
}
