SUBSCRIPTION_FORM_SUBMISSION = {
    "email": "member_test@test.com",
    "firstname": "member name",
    "lastname": "member surname",
    "gender": "male",
    "birthdate": "22/03/1983",
    "phone": "1234",
    "lang": "6",
    # "vat": "47731166W",
    "vat": "71838114Y",
    "address": "address test",
    "city": "city test",
    "zip_code": "08301",
    "country_id": "68",
    "ordered_parts": "2",
    "privacy_policy": "on",
    "internal_rules": "on",
    "financial_risk": "on",
    "generic_rules": "on",
    "payment_method": "sepa",
    "iban": "ES0820385793089381465771",
    "conditions_payment": "on",
}

SUBSCRIPTION_FORM_SUBMISSION_COMPANY_MEMBER = {
    "email": "member_test@test.com",
    "firstname": "member name",
    "lastname": "member surname",
    "gender": "male",
    "birthdate": "22/03/1983",
    "phone": "1234",
    "lang": "6",
    "vat": "90793973R",
    "address": "address test",
    "city": "city test",
    "zip_code": "08301",
    "country_id": "68",
    "ordered_parts": "2",
    "privacy_policy": "on",
    "internal_rules": "on",
    "financial_risk": "on",
    "generic_rules": "on",
    "payment_method": "sepa",
    "iban": "ES0820385793089381465771",
    "conditions_payment": "on",
    "company_name": "company name",
    "company_email": "company_member_test@test.com",
    "contact_person_function": "contact person function",
}

SUBSCRIPTION_FORM_SUBMISSION_VOLUNTARY = {
    "vat": "43549978F",
    "email": "ignacio@fake.com",
    "phone": "603903268",
    "ordered_parts": "2",
    "privacy_policy": "on",
    "internal_rules": "on",
    "financial_risk": "on",
    "generic_rules": "on",
    "payment_method": "transfer",
    "iban": "",
    "conditions_payment": "on",
}
