SUBSCRIPTION_FORM_SUBMISSION = {
    "email": "member_test@test.com",
    "firstname": "member name",
    "lastname": "member surname",
    "gender": "male",
    "birthdate": "22/03/1983",
    "phone": "1234",
    "lang": "6",
    # "vat": "47731166W",
    "vat": "71838114Y",
    "address": "address test",
    "city": "city test",
    "zip_code": "08301",
    "country_id": "68",
    "ordered_parts": "2",
    "privacy_policy": "on",
    "internal_rules": "on",
    "financial_risk": "on",
    "generic_rules": "on",
    "payment_method": "sepa",
    "iban": "ES0820385793089381465771",
    "conditions_payment": "on",
}

SUBSCRIPTION_FORM_SUBMISSION_COMPANY_MEMBER = {
    "email": "member_test@test.com",
    "firstname": "member name",
    "lastname": "member surname",
    "gender": "male",
    "birthdate": "22/03/1983",
    "phone": "1234",
    "lang": "6",
    "vat": "90793973R",
    "address": "address test",
    "city": "city test",
    "zip_code": "08301",
    "country_id": "68",
    "ordered_parts": "2",
    "privacy_policy": "on",
    "internal_rules": "on",
    "financial_risk": "on",
    "generic_rules": "on",
    "payment_method": "sepa",
    "iban": "ES0820385793089381465771",
    "conditions_payment": "on",
    "company_name": "company name",
    "company_email": "company_member_test@test.com",
    "contact_person_function": "contact person function",
}

SUBSCRIPTION_FORM_SUBMISSION_VOLUNTARY = {
    "vat": "43549978F",
    "email": "ignacio@fake.com",
    "phone": "603903268",
    "ordered_parts": "2",
    "privacy_policy": "on",
    "internal_rules": "on",
    "financial_risk": "on",
    "generic_rules": "on",
    "payment_method": "transfer",
    "iban": "",
    "conditions_payment": "on",
}

SUBSCRIPTION_REQUEST_PARAMS = {
    "active": True,
    "address": "j",
    "already_cooperator": False,
    "birthdate": "2026-03-10",
    "capital_release_request": [],
    "capital_release_request_date": False,
    "city": "girona",
    "company_email": False,
    "company_id": 13,
    "company_name": False,
    "company_register_number": False,
    "company_type": False,
    "contact_person_function": False,
    "country_id": 68,
    "data_policy_approved": True,
    "date": "2026-03-10",
    "email": "foo.bar@somenergia.coop",
    "financial_risk_approved": True,
    "firstname": "Foo",
    "gender": "other",
    "generic_rules_approved": True,
    "iban": "ES11 2010 3896 6052 7677 5835",
    "internal_rules_approved": True,
    "is_company": False,
    "is_operation": False,
    "lang": "es_ES",
    "lastname": "Bar Tolo",
    "mandate_approved": True,
    "mandate_id": False,
    "ordered_parts": 1,
    "partner_id": False,
    "payment_mode_id": 31,
    "phone": "67",
    "service_invoicing_sale_order_id": False,
    "share_product_id": 22,
    "share_unit_price": 100,
    "skip_iban_control": False,
    "source": "manual",
    "state": "draft",
    "subscription_amount": 100,
    "type": "new",
    "vat": "12345678Z",
    "zip_code": "25518",
}
