from . import cm_coordinates_mixin
from . import external_id_mixin
from . import account_move
from . import auth_oauth_provider
from . import user_current_company_mixin
from . import cm_filter
from . import cm_place
from . import community_energy_action
from . import energy_action
from . import landing_cooperator_button
from . import landing_page
from . import mail_channel
from . import mail_message
from . import mail_template
from . import product
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_partner_bank
from . import res_users
from . import res_users_role
from . import utm_source
