from . import cm_coordinates_mixin
from . import external_id_mixin
from . import auth_oauth_provider
from . import account_chart_template
from . import landing_page
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_partner_bank
from . import res_users
from . import res_users_role
from . import subscription_request
from . import product
from . import utm_source
from . import crm_lead_metadata_line
from . import crm_lead
from . import account_move
from . import operation_request
