from collections import namedtuple

from ..config import (
    COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
    PLATFORM_PACK_PRODUCT_CATEG_REF,
    PLATFORM_SERVICE_PRODUCT_CATEG_REF,
    RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
    RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
    SELFCONSUMPTION_PACK_PRODUCT_CATEG_REF,
    SELFCONSUMPTION_SERVICE_PRODUCT_CATEG_REF,
    SHARE_RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
)
from ..schemas import (
    PackProductCreationData,
    ServiceProductCreationData,
    ServiceProductExistingData,
)

PackProductDataTestingCase = namedtuple(
    "PackProductDataTestingCase", list(PackProductCreationData.model_fields.keys())
)

ServiceProductCreationDataTestingCase = namedtuple(
    "ServiceProductCreationDataTestingCase",
    list(ServiceProductCreationData.model_fields.keys()),
)

ServiceProductExistingDataTestingCase = namedtuple(
    "ServiceProductExistingDataTestingCase",
    list(ServiceProductExistingData.model_fields.keys()),
)

ProductUtilsTestingCase = namedtuple(
    "ProductUtilsTestingCase", ["pack_product_case", "service_product_case"]
)

_PACK_PRODUCT_TESTING_CASES = {
    "fixed_prepaid_recurring_fee_pack": PackProductDataTestingCase(
        "Community 2",
        RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
        "Recurring fee pack test 1",
        "Recurring fee pack test 1 long description",
        "TP1",
        11,
        ["l10n_es.6_account_tax_template_s_iva21s"],
        "Recurring fee pack test 1 short name",
        True,
        False,
        False,
        False,
        "fixed",
        "pre-paid",
        False,
        False,
        "yearly",
        "22",
        "03",
    ),
    "fixed_prepaid_share_recurring_fee_pack": PackProductDataTestingCase(
        "Community 2",
        COOP_SHARE_RECURRING_FEE_PACK_PRODUCT_CATEG_REF,
        "Recurring fee share pack test 1",
        "Recurring fee share pack test 1 long description",
        "TP2",
        11,
        ["l10n_es.6_account_tax_template_s_iva21s"],
        "Recurring fee share pack test 1 short name",
        True,
        False,
        False,
        False,
        "fixed",
        "pre-paid",
        False,
        False,
        "yearly",
        "22",
        "03",
    ),
    "interval_prepaid_platform_pack": PackProductDataTestingCase(
        "Platform Company",
        PLATFORM_PACK_PRODUCT_CATEG_REF,
        "Platform pack test 1",
        "Platform pack test 1 long description",
        "TP3",
        0,
        ["l10n_es.1_account_tax_template_s_iva21s"],
        False,
        True,
        False,
        False,
        False,
        "interval",
        "pre-paid",
        2,
        "quarterly",
        False,
        False,
        False,
    ),
    "interval_prepaid_selfconsumption_pack": PackProductDataTestingCase(
        "Community 1",
        SELFCONSUMPTION_PACK_PRODUCT_CATEG_REF,
        "Selfconsumption pack test 1",
        "Selfconsumption pack test 1 long description",
        "TP4",
        0,
        ["l10n_es.5_account_tax_template_s_iva21s"],
        False,
        True,
        False,
        False,
        False,
        "interval",
        "pre-paid",
        2,
        "quarterly",
        False,
        False,
        False,
    ),
}

_SERVICE_PRODUCT_TESTING_CASES = {
    "recurring_fee_services": [
        ServiceProductCreationDataTestingCase(
            "Community 2",
            RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
            "Recurring fee service test 1",
            "Recurring fee service test 1 long description",
            "TS1",
            18,
            ["l10n_es.6_account_tax_template_s_iva21s"],
            False,
            True,
            False,
            False,
            False,
            "fixed",
            1,
            False,
        ),
        ServiceProductCreationDataTestingCase(
            "Community 2",
            RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
            "Recurring fee service test 2",
            "Recurring fee service test 2 long description",
            False,
            17,
            ["l10n_es.6_account_tax_template_s_iva21s"],
            False,
            True,
            False,
            False,
            False,
            "fixed",
            3,
            False,
        ),
    ],
    "share_recurring_fee_services": [
        ServiceProductCreationDataTestingCase(
            "Community 2",
            SHARE_RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
            "Share Recurring fee service test 1",
            "Share Recurring fee service test 1 long description",
            "TS1",
            18,
            ["l10n_es.4_account_tax_template_s_iva21s"],
            False,
            True,
            False,
            False,
            False,
            "fixed",
            1,
            False,
        ),
        ServiceProductCreationDataTestingCase(
            "Community 2",
            SHARE_RECURRING_FEE_SERVICE_PRODUCT_CATEG_REF,
            "Recurring fee service test 2",
            "Recurring fee service test 2 long description",
            False,
            17,
            ["l10n_es.4_account_tax_template_s_iva21s"],
            False,
            True,
            False,
            False,
            False,
            "fixed",
            3,
            False,
        ),
    ],
    "platform_services": [
        ServiceProductCreationDataTestingCase(
            "Platform Company",
            PLATFORM_SERVICE_PRODUCT_CATEG_REF,
            "Platform service test 1",
            "Platform service test 1 long description",
            "TS3",
            3,
            ["l10n_es.1_account_tax_template_s_iva21s"],
            False,
            True,
            False,
            False,
            False,
            "variable",
            False,
            "energy_communities_service_invoicing.active_community_members_formula",
        ),
        ServiceProductExistingDataTestingCase(
            "energy_communities_service_invoicing.demo_platform_service_product_template",
            15,
            "fixed",
            2,
            False,
        ),
    ],
    "selfconsumption_services": [
        ServiceProductCreationDataTestingCase(
            "Community 1",
            SELFCONSUMPTION_SERVICE_PRODUCT_CATEG_REF,
            "Selfconsumption service test 1",
            "Selfconsumption service test 1 long description",
            "TS4",
            8,
            ["l10n_es.5_account_tax_template_s_iva21s"],
            False,
            True,
            False,
            False,
            False,
            "fixed",
            1,
            False,
        )
    ],
}

_PRODUCT_UTILS_TESTING_CASES = {
    "fixed_prepaid_recurring_fee": ProductUtilsTestingCase(
        _PACK_PRODUCT_TESTING_CASES["fixed_prepaid_recurring_fee_pack"],
        _SERVICE_PRODUCT_TESTING_CASES["recurring_fee_services"],
    ),
    "fixed_prepaid_share_recurring_fee": ProductUtilsTestingCase(
        _PACK_PRODUCT_TESTING_CASES["fixed_prepaid_share_recurring_fee_pack"],
        _SERVICE_PRODUCT_TESTING_CASES["share_recurring_fee_services"],
    ),
    "fixed_prepaid_recurring_fee_no_services": ProductUtilsTestingCase(
        _PACK_PRODUCT_TESTING_CASES["fixed_prepaid_recurring_fee_pack"],
        [],
    ),
    "interval_prepaid_platform": ProductUtilsTestingCase(
        _PACK_PRODUCT_TESTING_CASES["interval_prepaid_platform_pack"],
        _SERVICE_PRODUCT_TESTING_CASES["platform_services"],
    ),
    "interval_prepaid_selfconsumption": ProductUtilsTestingCase(
        _PACK_PRODUCT_TESTING_CASES["interval_prepaid_selfconsumption_pack"],
        _SERVICE_PRODUCT_TESTING_CASES["selfconsumption_services"],
    ),
}
