from odoo import _

from odoo.addons.energy_communities.config import (
    STATE_ACTIVATION,
    STATE_ACTIVE,
    STATE_DRAFT,
    STATE_INSCRIPTION,
    STATE_LABELS,
)

# Project state constants
PROJECT_STATE_DRAFT = STATE_DRAFT
PROJECT_STATE_INSCRIPTION = STATE_INSCRIPTION
PROJECT_STATE_ACTIVATION = STATE_ACTIVATION
PROJECT_STATE_ACTIVE = STATE_ACTIVE

PROJECT_STATE_VALUES = [
    (PROJECT_STATE_DRAFT, STATE_LABELS[PROJECT_STATE_DRAFT]),
    (PROJECT_STATE_INSCRIPTION, STATE_LABELS[PROJECT_STATE_INSCRIPTION]),
    (PROJECT_STATE_ACTIVATION, STATE_LABELS[PROJECT_STATE_ACTIVATION]),
    (PROJECT_STATE_ACTIVE, STATE_LABELS[PROJECT_STATE_ACTIVE]),
]
PROJECT_STATE_DEFAULT_VALUE = PROJECT_STATE_DRAFT
